name = "Fronts"
uuid = "45b28afb-7f9c-4d83-a9c8-739861dbc76b"
authors = ["Gabriel S. Gerlero"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
