name: Update Docker Hub description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/DockerHubDescription.yml
  workflow_dispatch:
jobs:
  dockerhub-description:
    if: vars.DOCKERHUB_REPOSITORY
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Modify README.md for Docker Hub
      run: |
        sed -i "s|\"docs/src/assets/|\"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/docs/src/assets/|g" README.md
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ vars.DOCKERHUB_REPOSITORY }}
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
